apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  labels:
    app: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
        - name: data-ingestion
          image: smart-city/data-ingestion:latest
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
